import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import MainAppBar from '@/components/containers/navbar/MainNavBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <MainAppBar></MainAppBar>
        {children}
      </body>
    </html>
  )
}
